name: Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - run: |
          sudo apt-get update
          sudo apt-get install -y gcc
          pip install -r requirements.txt
          pip install pyinstaller

      - run: pyinstaller --onefile --distpath dist main.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: dist/main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
